### ISSUE TITLE
How to import exports from your old https://github.com/kckrinke/onetimepad

### ISSUE THREAD

**Issue by Wikinaut** [OneTimePass/OneTimePass#11]
Hi @kckrinke ,

I used your old code https://github.com/kckrinke/onetimepad and exported a backup file, but cannot decrypt that using (example)

```
openssl enc -aes-256-cbc -salt -d -in onetimepad.crypt -out onetimepad.clear
enter aes-256-cbc decryption password: xxxxxx
bad magic number
```
What's wrong here, please can you correct my command and help to decrypt the file?

Or is there a way to import the file from the old script to your new script?

**Comment by kckrinke** [comment]
@Wikinaut, I'm afraid I can't recall off-hand if the formats are portable and in fact, they're most likely not compatible with the reincarnation of this app.

With respect to the decryption, are you including the [WELL_KNOWN_SALT](https://github.com/kckrinke/onetimepad/blob/3a354c9e68cf48e31461d050a05a8653ff9223af/app/src/main/java/com/onest8/onetimepad/MainActivity.java#L615)?

**Comment by Wikinaut** [comment]
@kckrinke Yes, but the format of the (stored, exported) file looks strange in the beginning, as a formal header seems to be missing. Perhaps you can remember and check this, please and post the correct manual steps to decode a stored export file on the command line (with user supplied password and salt).

**Comment by Wikinaut** [comment]
@kckrinke A short tutorial (sequence of commands) how to perform a manual decoding would be great.

**Comment by noplanman** [comment]
> A short tutorial (sequence of commands) how to perform a manual decoding would be great.

Yes please!
