### ISSUE TITLE
Can not export data

### ISSUE THREAD

**Issue by corpix** [OneTimePass/OneTimePass#13]
It says `There was an error while trying to export the account information` and nothing more.

I have a `root` on my device and I have found the `/data/data/com.github.onetimepass/databases/secrets.dat`. Maybe I could somehow decrypt this file to export/backup my secrets?

**Comment by Uhter** [comment]
Same thing for me and it worked when I tried a shorter password. Try it!

**Comment by corpix** [comment]
Not worked for me

**Comment by Uhter** [comment]
I used 1234 password if you want to test it.
Unfortunately, the otpd export file isn't accepted by other import app… :(

**Comment by aurium** [comment]
I confirm @Uhter's tip. I finally could export using a short password.
