### ISSUE TITLE
Revoking permission at Export Data page causes app crashed 

### ISSUE THREAD

**Issue by DSOTM-pf** [OneTimePass/OneTimePass#14]
Hi, there, I've found a crash in OneTimePass_v1.2.2, which is downloaded from F-Droid.

### Reproduce crash
1. grant the storage permission and go to the export data page
2. go to the system setting and revoke the storage permission
3. go back app, then the app crashes

Here is the video about how I found this crash.

https://user-images.githubusercontent.com/26241319/127286402-21307586-b723-48ef-a701-10c16a0068aa.mp4

@kckrinke 
Could you help me review this issue? Very thanks!!!

**Comment by kckrinke** [comment]
This app is actually unmaintained, see recent commits which reflect this and provide options for migrating away from OneTimePass.

This issue is a WONTFIX.
