### ISSUE TITLE
8 digit verification not working

### ISSUE THREAD

**Issue by ghost** [OneTimePass/OneTimePass#2]
e.g: otpauth://totp/xxx?secret=xxx&digits=8&algorithm=sha512&period=30

**Comment by kckrinke** [comment]
The algorithm currently does not support 8 digit codes. I'm not exactly sure what would be needed to implement support for the extra digits.

I'll have to research this more and see what I can come up with.

**Comment by ghost** [comment]
FreeOTP app supports it. (https://github.com/freeotp/freeotp-android) We could check its source code.

**Comment by kckrinke** [comment]
FreeOTP code is an option but I'd like to possibly find a nice library that can handle as many variations as possible.

Though, it is interesting that Steam is supported by FreeOTP as well.

**Comment by kckrinke** [comment]
Just a note that work has started on this though there's no ETA at this point. Will definitely be implemented for the next major release (1.3.0) and will include support for HOTP and STEAM. Using the freeotp code as the guide / example (and will credit the project accordingly).

**Comment by ghost** [comment]
Thank You for the improvements! :)
